
# Website info
name: 'Fasten Health Blog'
description: "Fasten securely connects your healthcare providers together, creating a personal health record that never leaves your hands"
logo: 'assets/images/banner.png'
favicon: 'assets/images/favicon.ico'
port                : 4000
host                : 127.0.0.1
baseurl: ''
disqus: 'fastenhealth'
email: 'hello@fastenhealth.com'

short_url: 'blog.fastenhealth.com'
#google_analytics: UA-69281367-1
#disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)

include: ["_pages"]

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap


authors:
  jason:
    name:           Jason Kulatunga
    site:           https://www.fastenhealth.com
    avatar:         assets/images/jason-avatar.png
    bio:            "Hi, I am Jason Kulatunga, the founder of Fasten Health"
    email:          jason@fastenhealth.com
    twitter:        https://twitter.com/fastenhealth
    linkedin:      https://www.linkedin.com/in/jason-kulatunga/



defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: jason
      avatar: assets/images/jason-avatar.png

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Jekyll configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-us'

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: fastenhealth
repo: blog
branch: main
#relative_source: ../jasper/
#destination: ../jasper-pages/
production_url:  https://blog.fastenhealth.com/
source_url:  https://github.com/fastenhealth/blog/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - .git


#logo: banner-transparent.png
#title: "Fasten Health Blog"
#remote_theme: just-the-docs/just-the-docs
#search_enabled: true
#aux_links:
#  "fastenhealth.com":
#    - "https://www.fastenhealth.com"
#last_edit_timestamp: true
#last_edit_time_format: "%b %e %Y at %I:%M %p"
#back_to_top: true
#back_to_top_text: "Back to top"
#footer_content: 'Copyright &copy; 2022 Fasten Health.'
#gh_edit_link: true
#gh_edit_link_text: "Prior Versions"
#gh_edit_repository: "https://github.com/fastenhealth/blog"
#gh_edit_branch: "main"
#gh_edit_view_mode: "commits"
#color_scheme: light
#callouts:
#  warning:
#    title: Warning
#    color: red
